export const LECTURE_LIST_REQUEST = 'LECTURE_LIST_REQUEST'
export const LECTURE_LIST_SUCCESS = 'LECTURE_LIST_SUCCESS'
export const LECTURE_LIST_FAIL = 'LECTURE_LIST_FAIL'

export const LECTURE_DETAILS_REQUEST = 'LECTURE_DETAILS_REQUEST'
export const LECTURE_DETAILS_SUCCESS = 'LECTURE_DETAILS_SUCCESS'
export const LECTURE_DETAILS_FAIL = 'LECTURE_DETAILS_FAIL'

export const LECTURE_DELETE_REQUEST = 'LECTURE_DELETE_REQUEST'
export const LECTURE_DELETE_SUCCESS = 'LECTURE_DELETE_SUCCESS'
export const LECTURE_DELETE_FAIL = 'LECTURE_DELETE_FAIL'

export const LECTURE_CREATE_REQUEST = 'LECTURE_CREATE_REQUEST'
export const LECTURE_CREATE_SUCCESS = 'LECTURE_CREATE_SUCCESS'
export const LECTURE_CREATE_FAIL = 'LECTURE_CREATE_FAIL'
export const LECTURE_CREATE_RESET = 'LECTURE_CREATE_RESET'

export const LECTURE_UPDATE_REQUEST = 'LECTURE_UPDATE_REQUEST'
export const LECTURE_UPDATE_SUCCESS = 'LECTURE_UPDATE_SUCCESS'
export const LECTURE_UPDATE_FAIL = 'LECTURE_UPDATE_FAIL'
export const LECTURE_UPDATE_RESET = 'LECTURE_UPDATE_RESET'

export const LECTURE_CREATE_REVIEW_REQUEST = 'LECTURE_CREATE_REVIEW_REQUEST'
export const LECTURE_CREATE_REVIEW_SUCCESS = 'LECTURE_CREATE_REVIEW_SUCCESS'
export const LECTURE_CREATE_REVIEW_FAIL = 'LECTURE_CREATE_REVIEW_FAIL'
export const LECTURE_CREATE_REVIEW_RESET = 'LECTURE_CREATE_REVIEW_RESET'

export const LECTURE_TOP_REQUEST = 'LECTURE_TOP_REQUEST'
export const LECTURE_TOP_SUCCESS = 'LECTURE_TOP_SUCCESS'
export const LECTURE_TOP_FAIL = 'LECTURE_TOP_FAIL'